[build]
  publish = "."
  command = "echo 'No build command needed for static site'"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, DELETE"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Content-Security-Policy = "frame-ancestors 'self' https://agent.d-id.com https://*.d-id.com"
    X-Frame-Options = "ALLOW-FROM https://agent.d-id.com" 